# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/benni/dev/echessboard/echessboard_vivado/echessboar_vivado.srcs/sources_1/ip/vga_framebuf_mem/vga_framebuf_mem.xci
# IP: The module: 'vga_framebuf_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benni/dev/echessboard/echessboard_vivado/echessboar_vivado.gen/sources_1/ip/vga_framebuf_mem/vga_framebuf_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_framebuf_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/benni/dev/echessboard/echessboard_vivado/echessboar_vivado.srcs/sources_1/ip/vga_framebuf_mem/vga_framebuf_mem.xci
# IP: The module: 'vga_framebuf_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/benni/dev/echessboard/echessboard_vivado/echessboar_vivado.gen/sources_1/ip/vga_framebuf_mem/vga_framebuf_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_framebuf_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
